<?php
    /* @var $this Mage_Core_Block_Template */
    /* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
    $catalogSearchHelper = $this->helper('catalogsearch');
?>

<a href="#search" class="btn btn-quaternary btn-search js-fancybox-special" data-wrap-css="fancybox-bare">
    <i class="glyphicon glyphicon-search"></i>
    <?php echo $this->__('Search'); ?>
</a>

<form id="search-form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get" style="display: none;">
    <div class="form-search">
        <div class="input-group">
            <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text form-control" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>">
            <span class="input-group-btn">
                <button type="submit" title="<?php echo $this->__('Search') ?>" class="btn btn-default"><span><span><?php echo $this->__('Search') ?></span></span></button>
            </span>
        </div>


        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
            searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
        </script>
    </div>
</form>
