<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<header class="site-header <?php echo $this->getHeaderClass(); ?>">
    <?php echo $this->getChildHtml('header.top') ?>

    <div class="header-content">
        <div class="header-inner">
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"></a>

            <div class="quick-access">
                <?php echo $this->getChildHtml('topLinks') ?>
                <?php echo $this->getChildHtml('store_language') ?>
                <?php echo $this->getChildHtml('topSearch') ?>
                <?php echo $this->getChildHtml('quickAccess') ?>
            </div>

            <?php echo $this->getChildHtml('header.extra'); ?>
        </div>
    </div>

    <?php echo $this->getChildHtml('topMenu') ?>
</header>
