<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>

<?php $_menu = $this->getHtml('level-top') ?>

<?php if ($_menu): ?>
    <div class="site-navigation">
        <div class="navigation-content">
            <div class="navigation-inner">
                <nav class="navbar navbar-main" role="navigation">
                    <div class="collapse navbar-collapse" id="site-navigation">
                        <ul class="nav navbar-nav">
                            <?php echo $_menu ?>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
<?php endif ?>

