<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="container">
    <header class="site-header">
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"></a>

        <div class="quick-access">
            <div class="clearfix">
                <?php echo $this->getChildHtml('topLinks') ?>
                <?php echo $this->getChildHtml('store_language') ?>
            </div>
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>
        
        <?php echo $this->getChildHtml('topContainer'); ?>
    </header>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
