<?php
    /* @var $this Mage_Core_Block_Template */
    /* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
    $catalogSearchHelper = $this->helper('catalogsearch');
?>

<a href="#search-form" class="btn btn-search js-fancybox-special" data-wrap-css="fancybox-bare">
    <i class="glyphicon glyphicon-search"></i>
    <?php echo $this->__('Search'); ?>
</a>

<form id="search-form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get" style="display: none;">
    <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text form-control" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />

    <button type="submit" title="<?php echo $this->__('Search') ?>" class="btn btn-default">
        <span><span><?php echo $this->__('Search') ?></span></span>
    </button>
</form>
